# WSL2 Migration - Quick Start Guide
# ===================================
# Run this script to begin the WSL2 migration process
#
# Purpose: Interactive guide through all installation steps
# Author: Generated by Claude Code
# Date: 2025-11-16

$ErrorActionPreference = "Stop"

Write-Host ""
Write-Host "================================================================" -ForegroundColor Cyan
Write-Host "    WSL2 Migration: Aider & Codex CLI" -ForegroundColor Cyan
Write-Host "    Quick Start Guide" -ForegroundColor Cyan
Write-Host "================================================================" -ForegroundColor Cyan
Write-Host ""
Write-Host "This interactive guide will help you:" -ForegroundColor Yellow
Write-Host "  1. Install WSL2 with Ubuntu" -ForegroundColor Gray
Write-Host "  2. Configure Ubuntu environment" -ForegroundColor Gray
Write-Host "  3. Install Aider and Codex CLI" -ForegroundColor Gray
Write-Host "  4. Set up PowerShell launcher functions" -ForegroundColor Gray
Write-Host "  5. Validate the complete setup" -ForegroundColor Gray
Write-Host ""
Write-Host "Estimated total time: 20-30 minutes" -ForegroundColor Gray
Write-Host ""
Write-Host "================================================================" -ForegroundColor Cyan
Write-Host ""

# Check if running as admin
$isAdmin = ([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)

Write-Host "Current Status:" -ForegroundColor Cyan
Write-Host "  Administrator: " -NoNewline
if ($isAdmin) {
    Write-Host "Yes" -ForegroundColor Green
} else {
    Write-Host "No" -ForegroundColor Yellow
}

# Check WSL status
Write-Host "  WSL Installed: " -NoNewline
try {
    $wslStatus = wsl --status 2>&1
    Write-Host "Yes" -ForegroundColor Green
    $wslInstalled = $true
} catch {
    Write-Host "No" -ForegroundColor Red
    $wslInstalled = $false
}

Write-Host ""
Write-Host "================================================================" -ForegroundColor Cyan
Write-Host ""

# Determine starting point
if (-not $wslInstalled) {
    Write-Host "STEP 1: Install WSL2" -ForegroundColor Yellow
    Write-Host "----------------------------------------------------------------" -ForegroundColor Gray
    Write-Host ""
    Write-Host "WSL2 is not currently installed." -ForegroundColor Yellow
    Write-Host ""
    Write-Host "To install WSL2, you need to:" -ForegroundColor Cyan
    Write-Host ""
    Write-Host "1. Close this window" -ForegroundColor White
    Write-Host "2. Right-click PowerShell and select 'Run as Administrator'" -ForegroundColor White
    Write-Host "3. Run: .\WSL-Install-Step1-ADMIN-REQUIRED.ps1" -ForegroundColor White
    Write-Host "4. Follow the prompts and reboot when asked" -ForegroundColor White
    Write-Host "5. After reboot, complete Ubuntu first-time setup" -ForegroundColor White
    Write-Host "6. Run this script again (.\START-HERE.ps1)" -ForegroundColor White
    Write-Host ""
    Write-Host "----------------------------------------------------------------" -ForegroundColor Gray
    Write-Host ""

    if (-not $isAdmin) {
        Write-Host "NOTE: You are not running as Administrator." -ForegroundColor Red
        Write-Host "      WSL installation REQUIRES administrator privileges." -ForegroundColor Red
        Write-Host ""
    }

    Write-Host "Would you like to:" -ForegroundColor Cyan
    Write-Host "  [1] Open documentation (WSL-INSTALLATION-GUIDE.md)" -ForegroundColor Gray
    Write-Host "  [2] Exit and run Step 1 manually" -ForegroundColor Gray
    Write-Host ""
    $choice = Read-Host "Enter choice (1 or 2)"

    if ($choice -eq "1") {
        Start-Process "WSL-INSTALLATION-GUIDE.md"
    }

    Write-Host ""
    Write-Host "Exiting. Please run WSL-Install-Step1-ADMIN-REQUIRED.ps1 as Administrator." -ForegroundColor Yellow
    Read-Host "Press Enter to exit"
    exit 0
}

# WSL is installed - continue with setup
Write-Host "✓ WSL2 is installed!" -ForegroundColor Green
Write-Host ""
Write-Host "Let's continue with the setup process." -ForegroundColor Cyan
Write-Host ""
Write-Host "================================================================" -ForegroundColor Cyan
Write-Host ""

# Check if Ubuntu is accessible
Write-Host "Checking Ubuntu accessibility..." -ForegroundColor Yellow
try {
    $user = wsl -d Ubuntu -- bash -c "whoami" 2>&1
    Write-Host "✓ Ubuntu is accessible (user: $user)" -ForegroundColor Green
    $ubuntuReady = $true
} catch {
    Write-Host "✗ Ubuntu is not accessible" -ForegroundColor Red
    Write-Host ""
    Write-Host "Please run: .\WSL-Install-Step2-Verify.ps1" -ForegroundColor Yellow
    Write-Host "Then run this script again." -ForegroundColor Yellow
    Read-Host "Press Enter to exit"
    exit 1
}

Write-Host ""
Write-Host "================================================================" -ForegroundColor Cyan
Write-Host ""

# Present remaining steps
Write-Host "REMAINING STEPS:" -ForegroundColor Cyan
Write-Host ""
Write-Host "Step 2: Verify WSL2 Installation" -ForegroundColor Yellow
Write-Host "  Script: .\WSL-Install-Step2-Verify.ps1" -ForegroundColor Gray
Write-Host "  Status: " -NoNewline
Write-Host "Recommended (optional if Ubuntu is working)" -ForegroundColor Cyan
Write-Host ""

Write-Host "Step 3: Configure Ubuntu Environment" -ForegroundColor Yellow
Write-Host "  Script: .\WSL-Setup-Step3-Ubuntu.ps1" -ForegroundColor Gray
Write-Host "  Status: " -NoNewline
Write-Host "Required" -ForegroundColor Red
Write-Host "  Time: ~5-10 minutes" -ForegroundColor Gray
Write-Host ""

Write-Host "Step 4: Install Aider" -ForegroundColor Yellow
Write-Host "  Script: .\WSL-Install-Step4-Aider.ps1" -ForegroundColor Gray
Write-Host "  Status: " -NoNewline
Write-Host "Required" -ForegroundColor Red
Write-Host "  Time: ~2-5 minutes" -ForegroundColor Gray
Write-Host ""

Write-Host "Step 5: Install Codex CLI" -ForegroundColor Yellow
Write-Host "  Script: .\WSL-Install-Step5-Codex.ps1" -ForegroundColor Gray
Write-Host "  Status: " -NoNewline
Write-Host "Required" -ForegroundColor Red
Write-Host "  Time: ~2-5 minutes" -ForegroundColor Gray
Write-Host ""

Write-Host "Step 6: Configure API Keys" -ForegroundColor Yellow
Write-Host "  Script: .\WSL-Setup-API-Keys.ps1" -ForegroundColor Gray
Write-Host "  Status: " -NoNewline
Write-Host "Optional (but recommended)" -ForegroundColor Cyan
Write-Host "  Time: ~1 minute" -ForegroundColor Gray
Write-Host ""

Write-Host "Step 7: Create PowerShell Launchers" -ForegroundColor Yellow
Write-Host "  Script: .\WSL-Create-Launchers.ps1" -ForegroundColor Gray
Write-Host "  Status: " -NoNewline
Write-Host "Optional (but recommended)" -ForegroundColor Cyan
Write-Host "  Time: ~1 minute" -ForegroundColor Gray
Write-Host ""

Write-Host "Step 8: Validate Installation" -ForegroundColor Yellow
Write-Host "  Script: .\WSL-Validate-All.ps1" -ForegroundColor Gray
Write-Host "  Status: " -NoNewline
Write-Host "Recommended" -ForegroundColor Cyan
Write-Host "  Time: ~1 minute" -ForegroundColor Gray
Write-Host ""

Write-Host "================================================================" -ForegroundColor Cyan
Write-Host ""

# Offer to run all steps automatically
Write-Host "AUTO-RUN OPTIONS:" -ForegroundColor Cyan
Write-Host ""
Write-Host "  [A] Run ALL steps automatically (Steps 3-8)" -ForegroundColor Green
Write-Host "  [M] Manual mode - I'll run each script myself" -ForegroundColor Yellow
Write-Host "  [D] Open documentation and exit" -ForegroundColor Cyan
Write-Host "  [X] Exit" -ForegroundColor Gray
Write-Host ""
$autoChoice = Read-Host "Enter choice (A/M/D/X)"

switch ($autoChoice.ToUpper()) {
    "A" {
        Write-Host ""
        Write-Host "================================================================" -ForegroundColor Cyan
        Write-Host "AUTO-RUN MODE" -ForegroundColor Green
        Write-Host "================================================================" -ForegroundColor Cyan
        Write-Host ""
        Write-Host "Running all setup steps automatically..." -ForegroundColor Yellow
        Write-Host "This will take approximately 15-20 minutes." -ForegroundColor Gray
        Write-Host ""
        Read-Host "Press Enter to begin (or Ctrl+C to cancel)"

        # Run each step
        Write-Host ""
        Write-Host "[1/6] Configuring Ubuntu environment..." -ForegroundColor Cyan
        & ".\WSL-Setup-Step3-Ubuntu.ps1"

        Write-Host ""
        Write-Host "[2/6] Installing Aider..." -ForegroundColor Cyan
        & ".\WSL-Install-Step4-Aider.ps1"

        Write-Host ""
        Write-Host "[3/6] Installing Codex CLI..." -ForegroundColor Cyan
        & ".\WSL-Install-Step5-Codex.ps1"

        Write-Host ""
        Write-Host "[4/6] Configuring API keys..." -ForegroundColor Cyan
        & ".\WSL-Setup-API-Keys.ps1"

        Write-Host ""
        Write-Host "[5/6] Creating PowerShell launchers..." -ForegroundColor Cyan
        & ".\WSL-Create-Launchers.ps1"

        Write-Host ""
        Write-Host "[6/6] Validating installation..." -ForegroundColor Cyan
        & ".\WSL-Validate-All.ps1"

        Write-Host ""
        Write-Host "================================================================" -ForegroundColor Cyan
        Write-Host "AUTO-RUN COMPLETE!" -ForegroundColor Green
        Write-Host "================================================================" -ForegroundColor Cyan
    }
    "M" {
        Write-Host ""
        Write-Host "MANUAL MODE" -ForegroundColor Yellow
        Write-Host "----------------------------------------------------------------" -ForegroundColor Gray
        Write-Host ""
        Write-Host "Run the following scripts in order:" -ForegroundColor Cyan
        Write-Host ""
        Write-Host "  .\WSL-Setup-Step3-Ubuntu.ps1" -ForegroundColor White
        Write-Host "  .\WSL-Install-Step4-Aider.ps1" -ForegroundColor White
        Write-Host "  .\WSL-Install-Step5-Codex.ps1" -ForegroundColor White
        Write-Host "  .\WSL-Setup-API-Keys.ps1" -ForegroundColor White
        Write-Host "  .\WSL-Create-Launchers.ps1" -ForegroundColor White
        Write-Host "  .\WSL-Validate-All.ps1" -ForegroundColor White
        Write-Host ""
        Write-Host "See WSL-INSTALLATION-GUIDE.md for detailed instructions." -ForegroundColor Gray
    }
    "D" {
        Write-Host ""
        Write-Host "Opening documentation..." -ForegroundColor Cyan
        Start-Process "WSL-INSTALLATION-GUIDE.md"
    }
    default {
        Write-Host ""
        Write-Host "Exiting." -ForegroundColor Yellow
    }
}

Write-Host ""
Read-Host "Press Enter to exit"
