# WSL2 Complete Validation Script
# ===================================
# Run this to verify all installations and configurations
#
# Purpose: Validate WSL2, Ubuntu, Aider, and Codex CLI setup
# Author: Generated by Claude Code
# Date: 2025-11-16

Write-Host "========================================" -ForegroundColor Cyan
Write-Host "WSL2 Complete Validation" -ForegroundColor Cyan
Write-Host "========================================" -ForegroundColor Cyan
Write-Host ""

$allPassed = $true

# Test 1: WSL Status
Write-Host "[1/10] Checking WSL installation..." -ForegroundColor Yellow
try {
    $wslStatus = wsl --status 2>&1 | Out-String
    Write-Host "✓ WSL is installed" -ForegroundColor Green
    Write-Host $wslStatus -ForegroundColor Gray
} catch {
    Write-Host "✗ WSL is not installed" -ForegroundColor Red
    $allPassed = $false
}

Write-Host ""

# Test 2: WSL Distributions
Write-Host "[2/10] Checking WSL distributions..." -ForegroundColor Yellow
try {
    $distros = wsl --list --verbose 2>&1 | Out-String
    Write-Host $distros -ForegroundColor Gray

    if ($distros -match "Ubuntu.*2") {
        Write-Host "✓ Ubuntu with WSL2 is installed" -ForegroundColor Green
    } else {
        Write-Host "✗ Ubuntu with WSL2 not found" -ForegroundColor Red
        $allPassed = $false
    }
} catch {
    Write-Host "✗ Could not list distributions" -ForegroundColor Red
    $allPassed = $false
}

Write-Host ""

# Test 3: WSL Connectivity
Write-Host "[3/10] Testing WSL Ubuntu connectivity..." -ForegroundColor Yellow
try {
    $user = wsl -d Ubuntu -- bash -c "whoami" 2>&1
    $pwd = wsl -d Ubuntu -- bash -c "pwd" 2>&1
    Write-Host "✓ Connected to Ubuntu as: $user" -ForegroundColor Green
    Write-Host "  Home directory: $pwd" -ForegroundColor Gray
} catch {
    Write-Host "✗ Cannot connect to Ubuntu" -ForegroundColor Red
    $allPassed = $false
}

Write-Host ""

# Test 4: Python Installation
Write-Host "[4/10] Checking Python installation..." -ForegroundColor Yellow
try {
    $pythonVersion = wsl -d Ubuntu -- bash -c "python3 --version" 2>&1
    Write-Host "✓ $pythonVersion" -ForegroundColor Green
} catch {
    Write-Host "✗ Python3 not found" -ForegroundColor Red
    $allPassed = $false
}

Write-Host ""

# Test 5: Git Installation
Write-Host "[5/10] Checking Git installation..." -ForegroundColor Yellow
try {
    $gitVersion = wsl -d Ubuntu -- bash -c "git --version" 2>&1
    Write-Host "✓ $gitVersion" -ForegroundColor Green
} catch {
    Write-Host "✗ Git not found" -ForegroundColor Red
    $allPassed = $false
}

Write-Host ""

# Test 6: Node.js Installation
Write-Host "[6/10] Checking Node.js installation..." -ForegroundColor Yellow
try {
    $nodeVersion = wsl -d Ubuntu -- bash -c "node --version" 2>&1
    $npmVersion = wsl -d Ubuntu -- bash -c "npm --version" 2>&1
    Write-Host "✓ Node.js $nodeVersion" -ForegroundColor Green
    Write-Host "  npm $npmVersion" -ForegroundColor Gray
} catch {
    Write-Host "✗ Node.js not found" -ForegroundColor Red
    $allPassed = $false
}

Write-Host ""

# Test 7: Directory Structure
Write-Host "[7/10] Checking directory structure..." -ForegroundColor Yellow
try {
    $hasCode = wsl -d Ubuntu -- bash -c "test -d ~/code && echo 'exists' || echo 'missing'" 2>&1
    $hasVenvs = wsl -d Ubuntu -- bash -c "test -d ~/.venvs && echo 'exists' || echo 'missing'" 2>&1

    if ($hasCode -eq 'exists') {
        Write-Host "✓ ~/code directory exists" -ForegroundColor Green
        $repos = wsl -d Ubuntu -- bash -c "ls -1 ~/code 2>/dev/null | wc -l" 2>&1
        Write-Host "  Contains $repos items" -ForegroundColor Gray
    } else {
        Write-Host "✗ ~/code directory missing" -ForegroundColor Red
        $allPassed = $false
    }

    if ($hasVenvs -eq 'exists') {
        Write-Host "✓ ~/.venvs directory exists" -ForegroundColor Green
    } else {
        Write-Host "✗ ~/.venvs directory missing" -ForegroundColor Red
        $allPassed = $false
    }
} catch {
    Write-Host "✗ Could not check directory structure" -ForegroundColor Red
    $allPassed = $false
}

Write-Host ""

# Test 8: Aider Installation
Write-Host "[8/10] Checking Aider installation..." -ForegroundColor Yellow
try {
    $aiderVersion = wsl -d Ubuntu -- bash -lc "source ~/.venvs/aider/bin/activate && aider --version 2>&1"
    if ($aiderVersion -match "aider|version|\d+\.\d+") {
        Write-Host "✓ Aider is installed: $aiderVersion" -ForegroundColor Green
    } else {
        Write-Host "✗ Aider version check returned unexpected output" -ForegroundColor Red
        Write-Host "  Output: $aiderVersion" -ForegroundColor Gray
        $allPassed = $false
    }
} catch {
    Write-Host "✗ Aider not found or not installed" -ForegroundColor Red
    Write-Host "  Error: $($_.Exception.Message)" -ForegroundColor Gray
    $allPassed = $false
}

Write-Host ""

# Test 9: Codex CLI Installation
Write-Host "[9/10] Checking Codex CLI installation..." -ForegroundColor Yellow
try {
    $codexCheck = wsl -d Ubuntu -- bash -lc "which codex 2>&1"
    if ($codexCheck -and $codexCheck -match "codex") {
        Write-Host "✓ Codex CLI is installed at: $codexCheck" -ForegroundColor Green

        # Try to get version (may require API key)
        $codexVersion = wsl -d Ubuntu -- bash -lc "codex --version 2>&1" 2>&1
        if ($codexVersion) {
            Write-Host "  Version info: $codexVersion" -ForegroundColor Gray
        }
    } else {
        Write-Host "✗ Codex CLI not found" -ForegroundColor Red
        $allPassed = $false
    }
} catch {
    Write-Host "✗ Codex CLI not found or not installed" -ForegroundColor Red
    $allPassed = $false
}

Write-Host ""

# Test 10: API Keys
Write-Host "[10/10] Checking API keys configuration..." -ForegroundColor Yellow
try {
    $openaiKey = wsl -d Ubuntu -- bash -lc "echo `$OPENAI_API_KEY 2>&1"
    $anthropicKey = wsl -d Ubuntu -- bash -lc "echo `$ANTHROPIC_API_KEY 2>&1"

    $hasOpenAI = ($openaiKey -and $openaiKey.Length -gt 10)
    $hasAnthropic = ($anthropicKey -and $anthropicKey.Length -gt 10)

    if ($hasOpenAI) {
        $masked = $openaiKey.Substring(0, [Math]::Min(7, $openaiKey.Length)) + "..." + $openaiKey.Substring([Math]::Max(0, $openaiKey.Length - 4))
        Write-Host "✓ OPENAI_API_KEY is set: $masked" -ForegroundColor Green
    } else {
        Write-Host "○ OPENAI_API_KEY is not set" -ForegroundColor Yellow
    }

    if ($hasAnthropic) {
        $masked = $anthropicKey.Substring(0, [Math]::Min(10, $anthropicKey.Length)) + "..." + $anthropicKey.Substring([Math]::Max(0, $anthropicKey.Length - 4))
        Write-Host "✓ ANTHROPIC_API_KEY is set: $masked" -ForegroundColor Green
    } else {
        Write-Host "○ ANTHROPIC_API_KEY is not set" -ForegroundColor Yellow
    }

    if (-not $hasOpenAI -and -not $hasAnthropic) {
        Write-Host "  Note: Run WSL-Setup-API-Keys.ps1 to configure API keys" -ForegroundColor Gray
    }
} catch {
    Write-Host "○ Could not check API keys" -ForegroundColor Yellow
}

Write-Host ""
Write-Host "========================================" -ForegroundColor Cyan

if ($allPassed) {
    Write-Host "ALL VALIDATIONS PASSED!" -ForegroundColor Green
    Write-Host "========================================" -ForegroundColor Cyan
    Write-Host ""
    Write-Host "Your WSL2 environment is fully configured!" -ForegroundColor Green
    Write-Host ""
    Write-Host "Next steps:" -ForegroundColor Cyan
    Write-Host "1. Reload PowerShell profile: . `$PROFILE" -ForegroundColor Gray
    Write-Host "2. Clone a repo to ~/code in WSL" -ForegroundColor Gray
    Write-Host "3. Try: aider-wsl <RepoName>" -ForegroundColor Gray
    Write-Host "4. Try: codex-wsl <RepoName>" -ForegroundColor Gray
} else {
    Write-Host "SOME VALIDATIONS FAILED" -ForegroundColor Red
    Write-Host "========================================" -ForegroundColor Cyan
    Write-Host ""
    Write-Host "Please review the failures above and:" -ForegroundColor Yellow
    Write-Host "1. Run the appropriate WSL-Install-Step*.ps1 scripts" -ForegroundColor Gray
    Write-Host "2. Check the installation guide: WSL-INSTALLATION-GUIDE.md" -ForegroundColor Gray
}

Write-Host ""
Read-Host "Press Enter to exit"
