# WSL2 PowerShell Launcher Functions
# ===================================
# Run this to add Aider and Codex launcher functions to your PowerShell profile
#
# Purpose: Create convenient Windows commands to launch WSL tools
# Author: Generated by Claude Code
# Date: 2025-11-16

Write-Host "========================================" -ForegroundColor Cyan
Write-Host "PowerShell Launcher Setup" -ForegroundColor Cyan
Write-Host "========================================" -ForegroundColor Cyan
Write-Host ""

# Detect PowerShell profile paths
$profilePaths = @(
    "$HOME\Documents\PowerShell\Microsoft.PowerShell_profile.ps1",  # PowerShell 7+
    "$HOME\Documents\WindowsPowerShell\Microsoft.PowerShell_profile.ps1"  # Windows PowerShell 5.1
)

Write-Host "This script will add launcher functions to your PowerShell profile:" -ForegroundColor Yellow
Write-Host ""
Write-Host "Functions to be added:" -ForegroundColor Cyan
Write-Host "  • aider-wsl <RepoName>     - Launch Aider in specified repo" -ForegroundColor Gray
Write-Host "  • aider-here-wsl           - Launch Aider in current directory's repo" -ForegroundColor Gray
Write-Host "  • codex-wsl <RepoName>     - Launch Codex in specified repo" -ForegroundColor Gray
Write-Host "  • codex-here-wsl           - Launch Codex in current directory's repo" -ForegroundColor Gray
Write-Host ""

# Ask for confirmation
$response = Read-Host "Do you want to add these functions? (y/n)"
if ($response -ne 'y' -and $response -ne 'Y') {
    Write-Host "Cancelled." -ForegroundColor Yellow
    Read-Host "Press Enter to exit"
    exit 0
}

# PowerShell launcher functions
$launcherFunctions = @'

# ============================================================
# WSL AI Tools Launcher Functions
# Added by WSL-Create-Launchers.ps1
# ============================================================

# Launch Aider in WSL for a specific repository
function aider-wsl {
    param(
        [Parameter(Mandatory = $true)]
        [string]$RepoName
    )

    $wslDistro = "Ubuntu"
    $wslPath = "/home/richg/code/$RepoName"

    Write-Host "Launching Aider in WSL for repo: $RepoName" -ForegroundColor Cyan
    wsl -d $wslDistro -- bash -lc "source ~/.venvs/aider/bin/activate && cd $wslPath && aider ."
}

# Launch Aider in WSL for the current directory (assumes matching repo structure)
function aider-here-wsl {
    $repoName = Split-Path -Leaf (Get-Location)
    $wslDistro = "Ubuntu"
    $wslPath = "/home/richg/code/$repoName"

    Write-Host "Launching Aider in WSL for repo: $repoName" -ForegroundColor Cyan
    wsl -d $wslDistro -- bash -lc "source ~/.venvs/aider/bin/activate && cd $wslPath && aider ."
}

# Launch Codex CLI in WSL for a specific repository
function codex-wsl {
    param(
        [Parameter(Mandatory = $true)]
        [string]$RepoName
    )

    $wslDistro = "Ubuntu"
    $wslPath = "/home/richg/code/$RepoName"

    Write-Host "Launching Codex CLI in WSL for repo: $RepoName" -ForegroundColor Cyan
    wsl -d $wslDistro -- bash -lc "cd $wslPath && codex"
}

# Launch Codex CLI in WSL for the current directory
function codex-here-wsl {
    $repoName = Split-Path -Leaf (Get-Location)
    $wslDistro = "Ubuntu"
    $wslPath = "/home/richg/code/$repoName"

    Write-Host "Launching Codex CLI in WSL for repo: $repoName" -ForegroundColor Cyan
    wsl -d $wslDistro -- bash -lc "cd $wslPath && codex"
}

# Helper function: Open WSL Ubuntu terminal in a specific repo
function wsl-code {
    param(
        [Parameter(Mandatory = $false)]
        [string]$RepoName = ""
    )

    $wslDistro = "Ubuntu"

    if ($RepoName) {
        $wslPath = "/home/richg/code/$RepoName"
        Write-Host "Opening WSL in repo: $RepoName" -ForegroundColor Cyan
        wsl -d $wslDistro -- bash -lc "cd $wslPath && exec bash"
    } else {
        Write-Host "Opening WSL in ~/code" -ForegroundColor Cyan
        wsl -d $wslDistro -- bash -lc "cd ~/code && exec bash"
    }
}

# Helper function: List repositories in WSL ~/code
function wsl-repos {
    $wslDistro = "Ubuntu"
    Write-Host "Repositories in ~/code:" -ForegroundColor Cyan
    wsl -d $wslDistro -- bash -lc "ls -la ~/code"
}

'@

# Add to each detected profile
$addedTo = @()
foreach ($profilePath in $profilePaths) {
    $profileDir = Split-Path -Parent $profilePath

    # Create profile directory if it doesn't exist
    if (-not (Test-Path $profileDir)) {
        Write-Host "Creating directory: $profileDir" -ForegroundColor Yellow
        New-Item -ItemType Directory -Path $profileDir -Force | Out-Null
    }

    # Create profile file if it doesn't exist
    if (-not (Test-Path $profilePath)) {
        Write-Host "Creating profile: $profilePath" -ForegroundColor Yellow
        New-Item -ItemType File -Path $profilePath -Force | Out-Null
    }

    # Backup existing profile
    $backupPath = "$profilePath.backup-$(Get-Date -Format 'yyyyMMdd-HHmmss')"
    Copy-Item -Path $profilePath -Destination $backupPath -Force
    Write-Host "Backup created: $backupPath" -ForegroundColor Gray

    # Check if functions already exist
    $profileContent = Get-Content -Path $profilePath -Raw -ErrorAction SilentlyContinue
    if ($profileContent -and $profileContent -match "aider-wsl") {
        Write-Host "WARNING: Launcher functions already exist in $profilePath" -ForegroundColor Yellow
        Write-Host "Skipping to avoid duplicates..." -ForegroundColor Gray
    } else {
        # Append launcher functions
        Add-Content -Path $profilePath -Value $launcherFunctions
        Write-Host "✓ Added launcher functions to: $profilePath" -ForegroundColor Green
        $addedTo += $profilePath
    }
}

Write-Host ""
Write-Host "========================================" -ForegroundColor Cyan
Write-Host "LAUNCHER SETUP COMPLETE!" -ForegroundColor Green
Write-Host "========================================" -ForegroundColor Cyan
Write-Host ""

if ($addedTo.Count -gt 0) {
    Write-Host "Functions added to:" -ForegroundColor Cyan
    foreach ($path in $addedTo) {
        Write-Host "  • $path" -ForegroundColor Gray
    }
    Write-Host ""
    Write-Host "To activate in current session, run:" -ForegroundColor Yellow
    Write-Host "  . `$PROFILE" -ForegroundColor Cyan
    Write-Host ""
    Write-Host "Or restart PowerShell" -ForegroundColor Gray
    Write-Host ""
}

Write-Host "Available commands after activation:" -ForegroundColor Cyan
Write-Host "  aider-wsl <RepoName>      - Launch Aider for a specific repo" -ForegroundColor Gray
Write-Host "  aider-here-wsl            - Launch Aider in current directory" -ForegroundColor Gray
Write-Host "  codex-wsl <RepoName>      - Launch Codex for a specific repo" -ForegroundColor Gray
Write-Host "  codex-here-wsl            - Launch Codex in current directory" -ForegroundColor Gray
Write-Host "  wsl-code [RepoName]       - Open WSL terminal in repo or ~/code" -ForegroundColor Gray
Write-Host "  wsl-repos                 - List all repos in ~/code" -ForegroundColor Gray
Write-Host ""
Write-Host "Example usage:" -ForegroundColor Cyan
Write-Host "  aider-wsl R_PIPELINE" -ForegroundColor Gray
Write-Host "  cd C:\Users\richg\code\MyProject; aider-here-wsl" -ForegroundColor Gray
Write-Host ""
Read-Host "Press Enter to continue"
