# WSL2 Aider Installation - Step 4 (FIXED)
# ===================================
# Run this to install Aider in WSL Ubuntu
#
# Purpose: Install Aider in a Python virtual environment
# Author: Generated by Claude Code
# Date: 2025-11-17
# Fixed: Auto-detects WSL user instead of hardcoding

Write-Host "========================================" -ForegroundColor Cyan
Write-Host "Aider Installation - Step 4 (FIXED)" -ForegroundColor Cyan
Write-Host "========================================" -ForegroundColor Cyan
Write-Host ""

# Test WSL connection and detect user
Write-Host "Testing WSL connection..." -ForegroundColor Yellow
try {
    $wslUser = wsl -d Ubuntu -- bash -c "whoami"
    $wslHome = wsl -d Ubuntu -- bash -c "echo \$HOME"
    Write-Host "✓ Connected to Ubuntu" -ForegroundColor Green
    Write-Host "  User: $wslUser" -ForegroundColor Gray
    Write-Host "  Home: $wslHome" -ForegroundColor Gray
} catch {
    Write-Host "ERROR: Cannot connect to Ubuntu" -ForegroundColor Red
    Read-Host "Press Enter to exit"
    exit 1
}

Write-Host ""
Write-Host "Installing Aider in Python virtual environment..." -ForegroundColor Cyan
Write-Host "This may take a few minutes..." -ForegroundColor Yellow
Write-Host ""

# Create the Aider installation script
$aiderInstallScript = @'
#!/bin/bash
set -e

echo "========================================="
echo "Aider Installation"
echo "========================================="
echo ""

# Check if Python3 is installed
if ! command -v python3 &> /dev/null; then
    echo "ERROR: Python3 is not installed"
    echo "Please run WSL-Setup-Step3-Ubuntu.ps1 first"
    exit 1
fi

# Create virtual environment for Aider
echo "Creating Python virtual environment for Aider..."
mkdir -p ~/.venvs
python3 -m venv ~/.venvs/aider

# Activate virtual environment and install Aider
echo ""
echo "Installing Aider..."
source ~/.venvs/aider/bin/activate

# Upgrade pip first
pip install --upgrade pip

# Install aider-chat
pip install aider-chat

# Verify installation
echo ""
echo "Verifying Aider installation..."
aider --version

echo ""
echo "✓ Aider installed successfully!"
echo ""
echo "Virtual environment location: ~/.venvs/aider"
echo "Current user: $(whoami)"
echo "Home directory: $HOME"
echo ""
echo "To use Aider in future sessions:"
echo "  1. source ~/.venvs/aider/bin/activate"
echo "  2. cd ~/code/your-project"
echo "  3. aider ."
echo ""
'@

# Save and execute the script
$tempScriptPath = "$env:TEMP\aider-install.sh"
$aiderInstallScript | Out-File -FilePath $tempScriptPath -Encoding UTF8 -NoNewline

try {
    Get-Content $tempScriptPath | wsl -d Ubuntu -- bash -c "cat > /tmp/aider-install.sh"
    wsl -d Ubuntu -- bash -c "chmod +x /tmp/aider-install.sh && /tmp/aider-install.sh"

    Write-Host ""
    Write-Host "✓ Aider installation completed!" -ForegroundColor Green
} catch {
    Write-Host ""
    Write-Host "ERROR: Aider installation failed" -ForegroundColor Red
    Write-Host $_.Exception.Message -ForegroundColor Red
    Read-Host "Press Enter to exit"
    exit 1
} finally {
    Remove-Item -Path $tempScriptPath -ErrorAction SilentlyContinue
}

Write-Host ""
Write-Host "========================================" -ForegroundColor Cyan
Write-Host "Testing Aider..." -ForegroundColor Cyan
Write-Host "========================================" -ForegroundColor Cyan
Write-Host ""

# Test Aider
try {
    $aiderVersion = wsl -d Ubuntu -- bash -lc "source ~/.venvs/aider/bin/activate && aider --version"
    Write-Host "✓ Aider version: $aiderVersion" -ForegroundColor Green
} catch {
    Write-Host "WARNING: Could not verify Aider version" -ForegroundColor Yellow
}

Write-Host ""
Write-Host "========================================" -ForegroundColor Cyan
Write-Host "NEXT STEPS:" -ForegroundColor Cyan
Write-Host "========================================" -ForegroundColor Cyan
Write-Host ""
Write-Host "1. Configure API keys: WSL-Setup-API-Keys.ps1" -ForegroundColor Yellow
Write-Host ""
Write-Host "2. Create PowerShell launcher: WSL-Create-Launchers-FIXED.ps1" -ForegroundColor Yellow
Write-Host "   (Use the FIXED version that auto-detects user)" -ForegroundColor Gray
Write-Host ""
Write-Host "NOTE: Codex CLI package doesn't exist - see README for alternatives" -ForegroundColor Yellow
Write-Host ""
Read-Host "Press Enter to continue"
