# WSL2 Codex CLI Installation - Step 5
# ===================================
# Run this to install Codex CLI in WSL Ubuntu
#
# Purpose: Install OpenAI Codex CLI via npm
# Author: Generated by Claude Code
# Date: 2025-11-16

Write-Host "========================================" -ForegroundColor Cyan
Write-Host "Codex CLI Installation - Step 5" -ForegroundColor Cyan
Write-Host "========================================" -ForegroundColor Cyan
Write-Host ""

# Test WSL connection
Write-Host "Testing WSL connection..." -ForegroundColor Yellow
try {
    $testResult = wsl -d Ubuntu -- bash -c "whoami"
    Write-Host "✓ Connected to Ubuntu as user: $testResult" -ForegroundColor Green
} catch {
    Write-Host "ERROR: Cannot connect to Ubuntu" -ForegroundColor Red
    Read-Host "Press Enter to exit"
    exit 1
}

Write-Host ""
Write-Host "Installing Codex CLI..." -ForegroundColor Cyan
Write-Host "This may take a few minutes..." -ForegroundColor Yellow
Write-Host ""

# Create the Codex installation script
$codexInstallScript = @'
#!/bin/bash
set -e

echo "========================================="
echo "Codex CLI Installation"
echo "========================================="
echo ""

# Check if Node.js is installed
if ! command -v node &> /dev/null; then
    echo "ERROR: Node.js is not installed"
    echo "Please run WSL-Setup-Step3-Ubuntu.ps1 first"
    exit 1
fi

echo "Node.js version: $(node --version)"
echo "npm version: $(npm --version)"
echo ""

# Install Codex CLI globally
echo "Installing Codex CLI globally via npm..."
npm install -g @openai/codex-cli

# Verify installation
echo ""
echo "Verifying Codex CLI installation..."
if command -v codex &> /dev/null; then
    codex --version
    echo ""
    echo "✓ Codex CLI installed successfully!"
else
    echo "WARNING: codex command not found in PATH"
    echo "You may need to add npm global bin to your PATH"
fi

echo ""
echo "Installation location:"
which codex || echo "  (not found in PATH)"
echo ""
'@

# Save and execute the script
$tempScriptPath = "$env:TEMP\codex-install.sh"
$codexInstallScript | Out-File -FilePath $tempScriptPath -Encoding UTF8 -NoNewline

try {
    wsl -d Ubuntu -- bash -c "cat > /tmp/codex-install.sh" < $tempScriptPath
    wsl -d Ubuntu -- bash -c "chmod +x /tmp/codex-install.sh && /tmp/codex-install.sh"

    Write-Host ""
    Write-Host "✓ Codex CLI installation completed!" -ForegroundColor Green
} catch {
    Write-Host ""
    Write-Host "ERROR: Codex CLI installation failed" -ForegroundColor Red
    Write-Host $_.Exception.Message -ForegroundColor Red
    Read-Host "Press Enter to exit"
    exit 1
} finally {
    Remove-Item -Path $tempScriptPath -ErrorAction SilentlyContinue
}

Write-Host ""
Write-Host "========================================" -ForegroundColor Cyan
Write-Host "Testing Codex CLI..." -ForegroundColor Cyan
Write-Host "========================================" -ForegroundColor Cyan
Write-Host ""

# Test Codex
try {
    $codexVersion = wsl -d Ubuntu -- bash -lc "codex --version 2>&1"
    Write-Host "✓ Codex version: $codexVersion" -ForegroundColor Green
} catch {
    Write-Host "WARNING: Could not verify Codex version" -ForegroundColor Yellow
    Write-Host "This is normal if Codex requires API key before showing version" -ForegroundColor Gray
}

Write-Host ""
Write-Host "========================================" -ForegroundColor Cyan
Write-Host "NEXT STEPS:" -ForegroundColor Cyan
Write-Host "========================================" -ForegroundColor Cyan
Write-Host ""
Write-Host "1. Configure API keys: WSL-Setup-API-Keys.ps1" -ForegroundColor Yellow
Write-Host "   (Required for Aider and Codex to function)" -ForegroundColor Gray
Write-Host ""
Write-Host "2. Create PowerShell launchers: WSL-Create-Launchers.ps1" -ForegroundColor Yellow
Write-Host "   (Allows you to launch tools from Windows)" -ForegroundColor Gray
Write-Host ""
Write-Host "3. Test installations: WSL-Validate-All.ps1" -ForegroundColor Yellow
Write-Host ""
Read-Host "Press Enter to continue"
