# WSL2 Installation Script - Step 2
# ===================================
# Run this AFTER rebooting and completing Ubuntu first-time setup
#
# Purpose: Verify WSL2 installation and configure defaults
# Author: Generated by Claude Code
# Date: 2025-11-16

Write-Host "========================================" -ForegroundColor Cyan
Write-Host "WSL2 Verification - Step 2" -ForegroundColor Cyan
Write-Host "========================================" -ForegroundColor Cyan
Write-Host ""

# Check WSL status
Write-Host "Checking WSL installation..." -ForegroundColor Yellow
try {
    $wslStatus = wsl --status 2>&1 | Out-String
    Write-Host $wslStatus -ForegroundColor Green
} catch {
    Write-Host "ERROR: WSL is not properly installed" -ForegroundColor Red
    Write-Host "Please run WSL-Install-Step1-ADMIN-REQUIRED.ps1 first" -ForegroundColor Yellow
    Read-Host "Press Enter to exit"
    exit 1
}

Write-Host ""
Write-Host "Listing installed distributions..." -ForegroundColor Yellow
$distros = wsl --list --verbose 2>&1 | Out-String
Write-Host $distros -ForegroundColor Cyan

Write-Host ""
Write-Host "Setting WSL2 as default version..." -ForegroundColor Yellow
try {
    wsl --set-default-version 2
    Write-Host "✓ WSL2 set as default version" -ForegroundColor Green
} catch {
    Write-Host "WARNING: Could not set default version" -ForegroundColor Yellow
}

# Check if Ubuntu is installed and is version 2
Write-Host ""
Write-Host "Verifying Ubuntu is using WSL2..." -ForegroundColor Yellow
$ubuntuInfo = wsl --list --verbose | Select-String -Pattern "Ubuntu"
if ($ubuntuInfo) {
    Write-Host $ubuntuInfo -ForegroundColor Cyan

    if ($ubuntuInfo -match "VERSION\s+1") {
        Write-Host ""
        Write-Host "WARNING: Ubuntu is running WSL version 1" -ForegroundColor Yellow
        Write-Host "Converting to WSL2..." -ForegroundColor Yellow
        wsl --set-version Ubuntu 2
        Write-Host "✓ Converted to WSL2 (this may take a few minutes)" -ForegroundColor Green
    } elseif ($ubuntuInfo -match "VERSION\s+2") {
        Write-Host "✓ Ubuntu is already using WSL2" -ForegroundColor Green
    }
} else {
    Write-Host "WARNING: Ubuntu distribution not found" -ForegroundColor Yellow
    Write-Host "You may need to install it manually from Microsoft Store" -ForegroundColor Yellow
}

Write-Host ""
Write-Host "Testing WSL connection..." -ForegroundColor Yellow
try {
    $testOutput = wsl -d Ubuntu -- bash -c "echo 'WSL Ubuntu connection successful'; whoami; pwd"
    Write-Host $testOutput -ForegroundColor Green
    Write-Host "✓ WSL Ubuntu is accessible" -ForegroundColor Green
} catch {
    Write-Host "ERROR: Could not connect to Ubuntu" -ForegroundColor Red
    Write-Host "Please ensure Ubuntu first-time setup is complete" -ForegroundColor Yellow
    Read-Host "Press Enter to exit"
    exit 1
}

Write-Host ""
Write-Host "========================================" -ForegroundColor Cyan
Write-Host "WSL2 VERIFICATION COMPLETE!" -ForegroundColor Green
Write-Host "========================================" -ForegroundColor Cyan
Write-Host ""
Write-Host "NEXT STEPS:" -ForegroundColor Cyan
Write-Host "1. Run: WSL-Setup-Step3-Ubuntu.ps1" -ForegroundColor Yellow
Write-Host "   (This will configure Ubuntu environment and install tools)" -ForegroundColor Gray
Write-Host ""
Read-Host "Press Enter to continue"
