# WSL2 PowerShell Launcher Functions (FIXED)
# ===================================
# Run this to add Aider launcher functions to your PowerShell profile
#
# Purpose: Create convenient Windows commands to launch WSL tools
# Author: Generated by Claude Code
# Date: 2025-11-17
# Fixed: Auto-detects WSL user instead of hardcoding richg

Write-Host "========================================" -ForegroundColor Cyan
Write-Host "PowerShell Launcher Setup (FIXED)" -ForegroundColor Cyan
Write-Host "========================================" -ForegroundColor Cyan
Write-Host ""

# Detect WSL user
Write-Host "Detecting WSL configuration..." -ForegroundColor Yellow
try {
    $wslUser = wsl -d Ubuntu -- bash -c "whoami"
    $wslHome = wsl -d Ubuntu -- bash -c "echo \$HOME"
    Write-Host "✓ WSL User: $wslUser" -ForegroundColor Green
    Write-Host "✓ WSL Home: $wslHome" -ForegroundColor Green
} catch {
    Write-Host "ERROR: Cannot connect to Ubuntu" -ForegroundColor Red
    Read-Host "Press Enter to exit"
    exit 1
}

Write-Host ""

# Detect PowerShell profile paths
$profilePaths = @(
    "$HOME\Documents\PowerShell\Microsoft.PowerShell_profile.ps1",  # PowerShell 7+
    "$HOME\Documents\WindowsPowerShell\Microsoft.PowerShell_profile.ps1"  # Windows PowerShell 5.1
)

Write-Host "This script will add launcher functions to your PowerShell profile:" -ForegroundColor Yellow
Write-Host ""
Write-Host "Functions to be added:" -ForegroundColor Cyan
Write-Host "  • aider-wsl <RepoName>     - Launch Aider in specified repo" -ForegroundColor Gray
Write-Host "  • aider-here-wsl           - Launch Aider in current directory's repo" -ForegroundColor Gray
Write-Host "  • wsl-code [RepoName]      - Open WSL terminal in repo" -ForegroundColor Gray
Write-Host "  • wsl-repos                - List repositories in ~/code" -ForegroundColor Gray
Write-Host ""
Write-Host "NOTE: Codex CLI functions removed (package doesn't exist)" -ForegroundColor Yellow
Write-Host ""

# Ask for confirmation
$response = Read-Host "Do you want to add these functions? (y/n)"
if ($response -ne 'y' -and $response -ne 'Y') {
    Write-Host "Cancelled." -ForegroundColor Yellow
    Read-Host "Press Enter to exit"
    exit 0
}

# PowerShell launcher functions with dynamic user detection
$launcherFunctions = @"

# ============================================================
# WSL AI Tools Launcher Functions (FIXED)
# Added by WSL-Create-Launchers-FIXED.ps1
# Auto-detects WSL user - no hardcoding
# ============================================================

# Get WSL user dynamically
function Get-WslUser {
    return wsl -d Ubuntu -- bash -c "whoami"
}

# Get WSL home directory dynamically
function Get-WslHome {
    return wsl -d Ubuntu -- bash -c "echo \`$HOME"
}

# Launch Aider in WSL for a specific repository
function aider-wsl {
    param(
        [Parameter(Mandatory = `$true)]
        [string]`$RepoName
    )

    `$wslDistro = "Ubuntu"
    `$wslHome = Get-WslHome
    `$wslPath = "`$wslHome/code/`$RepoName"

    Write-Host "Launching Aider in WSL for repo: `$RepoName" -ForegroundColor Cyan
    Write-Host "Path: `$wslPath" -ForegroundColor Gray
    wsl -d `$wslDistro -- bash -lc "source ~/.venvs/aider/bin/activate && cd `$wslPath && aider ."
}

# Launch Aider in WSL for the current directory (assumes matching repo structure)
function aider-here-wsl {
    `$repoName = Split-Path -Leaf (Get-Location)
    `$wslDistro = "Ubuntu"
    `$wslHome = Get-WslHome
    `$wslPath = "`$wslHome/code/`$repoName"

    Write-Host "Launching Aider in WSL for repo: `$repoName" -ForegroundColor Cyan
    Write-Host "Path: `$wslPath" -ForegroundColor Gray
    wsl -d `$wslDistro -- bash -lc "source ~/.venvs/aider/bin/activate && cd `$wslPath && aider ."
}

# Helper function: Open WSL Ubuntu terminal in a specific repo
function wsl-code {
    param(
        [Parameter(Mandatory = `$false)]
        [string]`$RepoName = ""
    )

    `$wslDistro = "Ubuntu"
    `$wslHome = Get-WslHome

    if (`$RepoName) {
        `$wslPath = "`$wslHome/code/`$RepoName"
        Write-Host "Opening WSL in repo: `$RepoName" -ForegroundColor Cyan
        Write-Host "Path: `$wslPath" -ForegroundColor Gray
        wsl -d `$wslDistro -- bash -lc "cd `$wslPath && exec bash"
    } else {
        Write-Host "Opening WSL in ~/code" -ForegroundColor Cyan
        wsl -d `$wslDistro -- bash -lc "cd ~/code && exec bash"
    }
}

# Helper function: List repositories in WSL ~/code
function wsl-repos {
    `$wslDistro = "Ubuntu"
    Write-Host "Repositories in ~/code:" -ForegroundColor Cyan
    wsl -d `$wslDistro -- bash -lc "ls -la ~/code"
}

# Helper function: Show WSL environment info
function wsl-info {
    `$wslUser = Get-WslUser
    `$wslHome = Get-WslHome
    Write-Host "WSL Environment:" -ForegroundColor Cyan
    Write-Host "  Distribution: Ubuntu" -ForegroundColor Gray
    Write-Host "  User: `$wslUser" -ForegroundColor Gray
    Write-Host "  Home: `$wslHome" -ForegroundColor Gray
}

"@

# Add to each detected profile
$addedTo = @()
foreach ($profilePath in $profilePaths) {
    $profileDir = Split-Path -Parent $profilePath

    # Create profile directory if it doesn't exist
    if (-not (Test-Path $profileDir)) {
        Write-Host "Creating directory: $profileDir" -ForegroundColor Yellow
        New-Item -ItemType Directory -Path $profileDir -Force | Out-Null
    }

    # Create profile file if it doesn't exist
    if (-not (Test-Path $profilePath)) {
        Write-Host "Creating profile: $profilePath" -ForegroundColor Yellow
        New-Item -ItemType File -Path $profilePath -Force | Out-Null
    }

    # Backup existing profile
    $backupPath = "$profilePath.backup-$(Get-Date -Format 'yyyyMMdd-HHmmss')"
    Copy-Item -Path $profilePath -Destination $backupPath -Force
    Write-Host "Backup created: $backupPath" -ForegroundColor Gray

    # Check if functions already exist
    $profileContent = Get-Content -Path $profilePath -Raw -ErrorAction SilentlyContinue
    if ($profileContent -and $profileContent -match "aider-wsl") {
        Write-Host "WARNING: Launcher functions already exist in $profilePath" -ForegroundColor Yellow
        $overwrite = Read-Host "Overwrite with FIXED version? (y/n)"
        if ($overwrite -eq 'y' -or $overwrite -eq 'Y') {
            # Remove old section and add new
            $profileContent = $profileContent -replace "(?s)# ============================================================\s*# WSL AI Tools Launcher Functions.*?(?=\r?\n\r?\n|$)", ""
            $profileContent = $profileContent.TrimEnd() + "`n" + $launcherFunctions
            Set-Content -Path $profilePath -Value $profileContent
            Write-Host "✓ Replaced launcher functions in: $profilePath" -ForegroundColor Green
            $addedTo += $profilePath
        }
    } else {
        # Append launcher functions
        Add-Content -Path $profilePath -Value $launcherFunctions
        Write-Host "✓ Added launcher functions to: $profilePath" -ForegroundColor Green
        $addedTo += $profilePath
    }
}

Write-Host ""
Write-Host "========================================" -ForegroundColor Cyan
Write-Host "LAUNCHER SETUP COMPLETE!" -ForegroundColor Green
Write-Host "========================================" -ForegroundColor Cyan
Write-Host ""

if ($addedTo.Count -gt 0) {
    Write-Host "Functions added/updated in:" -ForegroundColor Cyan
    foreach ($path in $addedTo) {
        Write-Host "  • $path" -ForegroundColor Gray
    }
    Write-Host ""
    Write-Host "To activate in current session, run:" -ForegroundColor Yellow
    Write-Host "  . `$PROFILE" -ForegroundColor Cyan
    Write-Host ""
    Write-Host "Or restart PowerShell" -ForegroundColor Gray
    Write-Host ""
}

Write-Host "Available commands after activation:" -ForegroundColor Cyan
Write-Host "  aider-wsl <RepoName>      - Launch Aider for a specific repo" -ForegroundColor Gray
Write-Host "  aider-here-wsl            - Launch Aider in current directory" -ForegroundColor Gray
Write-Host "  wsl-code [RepoName]       - Open WSL terminal in repo or ~/code" -ForegroundColor Gray
Write-Host "  wsl-repos                 - List all repos in ~/code" -ForegroundColor Gray
Write-Host "  wsl-info                  - Show WSL environment info" -ForegroundColor Gray
Write-Host ""
Write-Host "Example usage:" -ForegroundColor Cyan
Write-Host "  aider-wsl 'Complete AI Development Pipeline – Canonical Phase Plan'" -ForegroundColor Gray
Write-Host "  wsl-info" -ForegroundColor Gray
Write-Host ""
Read-Host "Press Enter to continue"
