# WSL2 Setup Script - Step 3
# ===================================
# Run this to configure Ubuntu environment and install necessary tools
#
# Purpose: Prepare Ubuntu for Aider and Codex CLI
# Author: Generated by Claude Code
# Date: 2025-11-16

Write-Host "========================================" -ForegroundColor Cyan
Write-Host "WSL2 Ubuntu Setup - Step 3" -ForegroundColor Cyan
Write-Host "========================================" -ForegroundColor Cyan
Write-Host ""

# Test WSL connection
Write-Host "Testing WSL connection..." -ForegroundColor Yellow
try {
    $testResult = wsl -d Ubuntu -- bash -c "whoami"
    Write-Host "✓ Connected to Ubuntu as user: $testResult" -ForegroundColor Green
} catch {
    Write-Host "ERROR: Cannot connect to Ubuntu" -ForegroundColor Red
    Write-Host "Please ensure WSL2 and Ubuntu are properly installed" -ForegroundColor Yellow
    Read-Host "Press Enter to exit"
    exit 1
}

Write-Host ""
Write-Host "This script will configure Ubuntu with:" -ForegroundColor Cyan
Write-Host "  • System updates (apt update && upgrade)" -ForegroundColor Gray
Write-Host "  • Python 3, pip, venv, git" -ForegroundColor Gray
Write-Host "  • Node.js and npm (for Codex CLI)" -ForegroundColor Gray
Write-Host "  • UTF-8 locale configuration" -ForegroundColor Gray
Write-Host "  • ~/code directory structure" -ForegroundColor Gray
Write-Host "  • ~/.venvs directory for Python virtual environments" -ForegroundColor Gray
Write-Host ""
Write-Host "This may take several minutes..." -ForegroundColor Yellow
Write-Host ""
Read-Host "Press Enter to continue or Ctrl+C to cancel"

# Create the setup script that will run inside WSL
$ubuntuSetupScript = @'
#!/bin/bash
set -e

echo "========================================="
echo "Ubuntu Environment Setup"
echo "========================================="
echo ""

# Update package lists
echo "Updating package lists..."
sudo apt update

# Upgrade existing packages
echo ""
echo "Upgrading existing packages (this may take a while)..."
sudo apt upgrade -y

# Install core tools
echo ""
echo "Installing core tools (Python, pip, git, venv)..."
sudo apt install -y python3 python3-pip python3-venv git

# Install Node.js and npm (for Codex CLI)
echo ""
echo "Installing Node.js and npm..."
# Using NodeSource for latest LTS version
curl -fsSL https://deb.nodesource.com/setup_lts.x | sudo -E bash -
sudo apt install -y nodejs

# Verify installations
echo ""
echo "Verifying installations..."
echo "  Python: $(python3 --version)"
echo "  pip: $(pip3 --version)"
echo "  git: $(git --version)"
echo "  Node.js: $(node --version)"
echo "  npm: $(npm --version)"

# Configure UTF-8 locale
echo ""
echo "Configuring UTF-8 locale..."
sudo update-locale LANG=en_US.UTF-8

# Check current locale
echo "Current locale settings:"
locale | grep -E "LANG|LC_ALL"

# Create directory structure
echo ""
echo "Creating directory structure..."
mkdir -p ~/code
mkdir -p ~/.venvs

echo ""
echo "✓ Ubuntu environment setup complete!"
echo ""
echo "Directory structure:"
ls -la ~ | grep -E "code|venvs"

echo ""
echo "========================================="
echo "Setup Complete!"
echo "========================================="
'@

# Save the script to a temp location accessible from WSL
$tempScriptPath = "$env:TEMP\ubuntu-setup.sh"
$ubuntuSetupScript | Out-File -FilePath $tempScriptPath -Encoding UTF8 -NoNewline

# Copy to WSL and execute
Write-Host "Executing Ubuntu setup script..." -ForegroundColor Cyan
Write-Host ""
try {
    # Copy script to WSL home directory
    wsl -d Ubuntu -- bash -c "cat > /tmp/ubuntu-setup.sh" < $tempScriptPath

    # Make it executable and run it
    wsl -d Ubuntu -- bash -c "chmod +x /tmp/ubuntu-setup.sh && /tmp/ubuntu-setup.sh"

    Write-Host ""
    Write-Host "✓ Ubuntu setup completed successfully!" -ForegroundColor Green
} catch {
    Write-Host ""
    Write-Host "ERROR: Ubuntu setup failed" -ForegroundColor Red
    Write-Host $_.Exception.Message -ForegroundColor Red
    Read-Host "Press Enter to exit"
    exit 1
} finally {
    # Cleanup temp file
    Remove-Item -Path $tempScriptPath -ErrorAction SilentlyContinue
}

Write-Host ""
Write-Host "========================================" -ForegroundColor Cyan
Write-Host "NEXT STEPS:" -ForegroundColor Cyan
Write-Host "========================================" -ForegroundColor Cyan
Write-Host ""
Write-Host "1. Run: WSL-Install-Step4-Aider.ps1" -ForegroundColor Yellow
Write-Host "   (This will install Aider in a Python virtual environment)" -ForegroundColor Gray
Write-Host ""
Write-Host "2. Run: WSL-Install-Step5-Codex.ps1" -ForegroundColor Yellow
Write-Host "   (This will install Codex CLI)" -ForegroundColor Gray
Write-Host ""
Write-Host "3. Configure API keys (see WSL-Setup-API-Keys.ps1)" -ForegroundColor Yellow
Write-Host ""
Read-Host "Press Enter to continue"
