# WSL2 Installation Script - Step 1
# ===================================
# THIS SCRIPT REQUIRES ADMINISTRATOR PRIVILEGES
# Right-click PowerShell and select "Run as Administrator" before running this script
#
# Purpose: Install WSL2 with Ubuntu on Windows
# Author: Generated by Claude Code
# Date: 2025-11-16

Write-Host "========================================" -ForegroundColor Cyan
Write-Host "WSL2 Installation - Step 1" -ForegroundColor Cyan
Write-Host "========================================" -ForegroundColor Cyan
Write-Host ""

# Check if running as administrator
$isAdmin = ([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)

if (-not $isAdmin) {
    Write-Host "ERROR: This script must be run as Administrator!" -ForegroundColor Red
    Write-Host "Please right-click PowerShell and select 'Run as Administrator'" -ForegroundColor Yellow
    Write-Host ""
    Read-Host "Press Enter to exit"
    exit 1
}

Write-Host "✓ Running with Administrator privileges" -ForegroundColor Green
Write-Host ""

# Check current WSL status
Write-Host "Checking current WSL status..." -ForegroundColor Yellow
try {
    $wslStatus = wsl --status 2>&1
    Write-Host "WSL is already installed:" -ForegroundColor Green
    Write-Host $wslStatus
    Write-Host ""
    Write-Host "Proceeding to verify configuration..." -ForegroundColor Yellow
} catch {
    Write-Host "WSL is not installed. Installing now..." -ForegroundColor Yellow
}

Write-Host ""
Write-Host "Installing WSL2 with Ubuntu..." -ForegroundColor Cyan
Write-Host "This may take several minutes..." -ForegroundColor Yellow
Write-Host ""

# Install WSL2
try {
    wsl --install
    Write-Host ""
    Write-Host "✓ WSL installation command completed!" -ForegroundColor Green
} catch {
    Write-Host "ERROR: Failed to install WSL" -ForegroundColor Red
    Write-Host $_.Exception.Message -ForegroundColor Red
    Read-Host "Press Enter to exit"
    exit 1
}

Write-Host ""
Write-Host "========================================" -ForegroundColor Cyan
Write-Host "NEXT STEPS:" -ForegroundColor Cyan
Write-Host "========================================" -ForegroundColor Cyan
Write-Host ""
Write-Host "1. You will likely need to REBOOT your system" -ForegroundColor Yellow
Write-Host "2. After reboot, Ubuntu will automatically launch and complete setup" -ForegroundColor Yellow
Write-Host "3. When prompted, create a UNIX username (suggested: richg)" -ForegroundColor Yellow
Write-Host "4. Set a password for that user" -ForegroundColor Yellow
Write-Host "5. After Ubuntu setup completes, run: WSL-Install-Step2-Verify.ps1" -ForegroundColor Yellow
Write-Host ""
Write-Host "Press Enter to continue (you may be prompted to reboot)..." -ForegroundColor Cyan
Read-Host
