# WSL2 API Keys Configuration
# ===================================
# Run this to configure API keys for Aider and Codex CLI
#
# Purpose: Set up environment variables for AI tool API access
# Author: Generated by Claude Code
# Date: 2025-11-16

Write-Host "========================================" -ForegroundColor Cyan
Write-Host "API Keys Configuration" -ForegroundColor Cyan
Write-Host "========================================" -ForegroundColor Cyan
Write-Host ""

Write-Host "This script will help you configure API keys for:" -ForegroundColor Yellow
Write-Host "  • OpenAI API (for Aider and Codex CLI)" -ForegroundColor Gray
Write-Host "  • Anthropic API (for Aider with Claude)" -ForegroundColor Gray
Write-Host ""
Write-Host "API keys will be stored in ~/.bashrc in WSL" -ForegroundColor Gray
Write-Host ""

# Ask if user wants to configure API keys
$response = Read-Host "Do you want to configure API keys now? (y/n)"
if ($response -ne 'y' -and $response -ne 'Y') {
    Write-Host "Skipping API key configuration." -ForegroundColor Yellow
    Write-Host "You can run this script again later or manually edit ~/.bashrc in WSL" -ForegroundColor Gray
    Read-Host "Press Enter to exit"
    exit 0
}

Write-Host ""
Write-Host "Enter your API keys (or press Enter to skip):" -ForegroundColor Cyan
Write-Host ""

# Collect API keys
$openaiKey = Read-Host "OpenAI API Key (sk-...)" -AsSecureString
$anthropicKey = Read-Host "Anthropic API Key (sk-ant-...)" -AsSecureString

# Convert secure strings to plain text for WSL
$openaiKeyPlain = [System.Runtime.InteropServices.Marshal]::PtrToStringAuto([System.Runtime.InteropServices.Marshal]::SecureStringToBSTR($openaiKey))
$anthropicKeyPlain = [System.Runtime.InteropServices.Marshal]::PtrToStringAuto([System.Runtime.InteropServices.Marshal]::SecureStringToBSTR($anthropicKey))

# Build the bash script to add keys to .bashrc
$apiKeyScript = @"
#!/bin/bash

echo ""
echo "Configuring API keys in ~/.bashrc..."

# Backup existing .bashrc
cp ~/.bashrc ~/.bashrc.backup

# Remove any existing API key exports (to avoid duplicates)
sed -i '/export OPENAI_API_KEY=/d' ~/.bashrc
sed -i '/export ANTHROPIC_API_KEY=/d' ~/.bashrc

# Add new API keys
echo "" >> ~/.bashrc
echo "# AI Tool API Keys (added by WSL-Setup-API-Keys.ps1)" >> ~/.bashrc
"@

if ($openaiKeyPlain) {
    $apiKeyScript += @"

echo 'export OPENAI_API_KEY="$openaiKeyPlain"' >> ~/.bashrc
"@
}

if ($anthropicKeyPlain) {
    $apiKeyScript += @"

echo 'export ANTHROPIC_API_KEY="$anthropicKeyPlain"' >> ~/.bashrc
"@
}

$apiKeyScript += @"

echo ""
echo "✓ API keys added to ~/.bashrc"
echo ""
echo "To activate in current session:"
echo "  source ~/.bashrc"
echo ""
echo "Verifying (keys will be masked):"
if [ ! -z "$openaiKeyPlain" ]; then
    echo "  OPENAI_API_KEY: ${openaiKeyPlain:0:7}...${openaiKeyPlain: -4}"
fi
if [ ! -z "$anthropicKeyPlain" ]; then
    echo "  ANTHROPIC_API_KEY: ${anthropicKeyPlain:0:10}...${anthropicKeyPlain: -4}"
fi
"@

# Save and execute the script
$tempScriptPath = "$env:TEMP\api-keys-setup.sh"
$apiKeyScript | Out-File -FilePath $tempScriptPath -Encoding UTF8 -NoNewline

try {
    Write-Host ""
    Write-Host "Configuring API keys in WSL..." -ForegroundColor Yellow

    wsl -d Ubuntu -- bash -c "cat > /tmp/api-keys-setup.sh" < $tempScriptPath
    wsl -d Ubuntu -- bash -c "chmod +x /tmp/api-keys-setup.sh && /tmp/api-keys-setup.sh"

    Write-Host ""
    Write-Host "✓ API keys configured successfully!" -ForegroundColor Green
    Write-Host ""
    Write-Host "Backup created at: ~/.bashrc.backup" -ForegroundColor Gray
} catch {
    Write-Host ""
    Write-Host "ERROR: Failed to configure API keys" -ForegroundColor Red
    Write-Host $_.Exception.Message -ForegroundColor Red
} finally {
    Remove-Item -Path $tempScriptPath -ErrorAction SilentlyContinue
}

Write-Host ""
Write-Host "========================================" -ForegroundColor Cyan
Write-Host "SECURITY NOTE:" -ForegroundColor Yellow
Write-Host "========================================" -ForegroundColor Cyan
Write-Host "• API keys are stored in plaintext in ~/.bashrc" -ForegroundColor Gray
Write-Host "• Make sure to keep your WSL filesystem secure" -ForegroundColor Gray
Write-Host "• Never commit .bashrc to a git repository" -ForegroundColor Gray
Write-Host "• Consider using a secrets manager for production use" -ForegroundColor Gray
Write-Host ""
Read-Host "Press Enter to continue"
