# FILE COPY BATCH TEMPLATE
# Pattern: EXEC-001 Batch File Creator for Module Migration
# DOC_ID: DOC-TEMPLATE-FILE-COPY-001

metadata:
  template_version: "1.0.0"
  pattern: EXEC-001
  purpose: eliminate_decisions_for_uet_module_copying
  decisions_eliminated: 5
  estimated_time_savings: 3_hours

parameters:
  source_files:
    type: list
    required: true
    example:
      - "UNIVERSAL_EXECUTION_TEMPLATES_FRAMEWORK/core/engine/orchestrator.py"
      - "UNIVERSAL_EXECUTION_TEMPLATES_FRAMEWORK/core/engine/scheduler.py"

  target_files:
    type: list
    required: true
    example:
      - "core/engine/uet_orchestrator.py"
      - "core/engine/uet_scheduler.py"

  import_modifications:
    type: dict
    required: false
    example:
      "from core.state.db": "from core.state.uet_db"
      "from ..adapters": "from .adapters"

  verification_imports:
    type: list
    required: true
    example:
      - "core.engine.uet_orchestrator"
      - "core.engine.uet_scheduler"

ground_truth_gates:
  gate_1_files_exist:
    command: "Test-Path {target_file}"
    expect: true
    failure_action: halt_and_report

  gate_2_imports_work:
    command: "python -c \"import {verification_import}\""
    expect_exit_code: 0
    failure_action: halt_and_report

  gate_3_no_syntax_errors:
    command: "python -m py_compile {target_file}"
    expect_exit_code: 0
    failure_action: halt_and_report

execution_sequence:
  - step: copy_files
    action: |
      for i in range(len(source_files)):
        copy(source_files[i], target_files[i])
        apply_import_modifications(target_files[i], import_modifications)

  - step: verify_batch
    gates: [gate_1_files_exist, gate_2_imports_work, gate_3_no_syntax_errors]

batch_configuration:
  batch_size: 6
  parallel: true
  fail_fast: true

anti_pattern_guards:
  hallucination_of_success:
    enabled: true
    rule: "Never mark file copy complete without gate_1_files_exist and gate_2_imports_work passing"

telemetry:
  track:
    - files_copied
    - import_modifications_applied
    - verification_pass_rate
    - time_per_file
  output: ".execution/telemetry.jsonl"
